[2017-04-07 08:00:07.352] [ERROR] console - Connection Error: Error: connection timeout
    at Db.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:169:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/creator/workspace/furuida/node_modules/mongodb/lib/db.js:1798:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb/lib/server.js:274:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:335:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:185:10)
    at Socket.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at Socket.emit (events.js:185:7)
    at Socket._onTimeout (net.js:339:8)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
[2017-04-07 08:00:37.687] [ERROR] console - Connection Error: { DisconnectedError: Ran out of retries trying to reconnect to "120.25.241.110:20000". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.
    at MongooseError.DisconnectedError (/Users/creator/workspace/furuida/node_modules/mongoose/lib/error/disconnected.js:21:11)
    at Server.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:64:31)
    at emitOne (events.js:101:20)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/topologies/server.js:317:16)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/pool.js:305:16)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:191:7)
    at Socket.<anonymous> (/Users/creator/workspace/furuida/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Socket.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1276:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  message: 'Ran out of retries trying to reconnect to "120.25.241.110:20000". Try setting `server.reconnectTries` and `server.reconnectInterval` to something higher.',
  name: 'DisconnectedError' }
